#file=open(r"C:\Users\varshini.anumalla\OneDrive - Acuvate Software Private Limited\Desktop\python excercises\day6_1\info.txt","r")
file =open("info.txt","r")
content=file.readlines()
print(content)
file.close()

file =open("info.txt","w")
file.write("Heloo goood morning \n this is varshini")
file.close()
file=open('info.txt',"r")
content=file.read()
print(content)
print()

file =open("info.txt","w")
file.write("Heloo goood morning \n this is varshini")
file.close()
file=open('info.txt',"r")
content=file.read()
print(content)
print()

file=open("info1.py","w")
file.write("from datetime import datetime\n")
file.write("now=datetime.now()\n")
file.write("print(now)")
file=open("info1.py","r")
content=file.read()
print(content)
exec(content)

